version: '3.8'

# networks:
#   challenger-net:
#     name: challenger-net

services:
  api:
    build: .
    ports:
      - "8080:8080"
    # networks:
    #   - challenger-net
    # environment:
    #   MONGO_URL: mongodb://mongodb:27017
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    # networks:
    #   - challenger-net